// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGhNeSBWIwWADw2f9v-Vj52k36A-RNlHc',
    appId: '1:390062465830:web:1e4b911442196f1d6917e7',
    messagingSenderId: '390062465830',
    projectId: 'flutter-chat-app-e9407',
    authDomain: 'flutter-chat-app-e9407.firebaseapp.com',
    storageBucket: 'flutter-chat-app-e9407.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_eEb_T7v6PBcoVf4d6lTl4tc5vbT7IKM',
    appId: '1:390062465830:android:1a0e3c1da9d7c3e46917e7',
    messagingSenderId: '390062465830',
    projectId: 'flutter-chat-app-e9407',
    storageBucket: 'flutter-chat-app-e9407.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBin0X2AiE6kPvexEsldwbTGTHigml0yGY',
    appId: '1:390062465830:ios:8cace8df3f3aae9c6917e7',
    messagingSenderId: '390062465830',
    projectId: 'flutter-chat-app-e9407',
    storageBucket: 'flutter-chat-app-e9407.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

}